name: "Wait Github Status Action"
description: "Wait for a Github status check, both internal (Actions) and external (eg. Jenkins)"
author: "Explorium DevOps Team"
branding:
  icon: battery-charging
  color: blue
inputs:
  name:
    description: 'The name of the check (eg. Lint, pr-head, Test, etc.)'
    required: true
    default: ''
  strict:
    description: 'Wait for it to finish successfully, not just end.'
    required: false
    default: 'true'
  timeout:
    description: 'If not empty, wait for that amount of seconds before failing.'
    required: false
    default: ''  
  seconds:
    description: 'Time to wait between each API wait poll check.'
    required: false
    default: '10'     
  token:
    description: 'Github API token'
    required: true
    default: ''     
  sha:
    description: 'You must insert the sha of the PR'
    required: true
    default: ${{ github.event.pull_request.head.sha }}
outputs:
  result:
    description: "Output from the action"    
runs:
  using: "docker"
  image: "Dockerfile"